name: objectbox_generator
description: ObjectBox Flutter / Dart database binding code generator - finds annotated entities and adds them to the ObjectBox DB model.
# Link to actual directory in repository so file links on pub.dev work.
repository: https://github.com/objectbox/objectbox-dart/tree/main/generator
homepage: https://objectbox.io
version: 4.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  objectbox: 4.1.0
  analyzer: ^7.3.0
  build: ^2.4.2
  collection: ^1.19.1
  dart_style: ^3.0.1
  glob: ^2.1.3
  path: ^1.9.1
  source_gen: ^2.0.0
  pubspec_parse: ^1.5.0
  yaml: ^3.1.3
  http: ^1.3.0
  pointycastle: ^3.9.1

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
  pub_semver: ^2.1.5
  package_config: ^2.1.1
  build_test: ^2.2.3
